sudo: required
services:
  - docker

before_install:
  - docker build -t iseeku4ever/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run iseeku4ever/react-test npm test -- --coverage

after_success:
  - docker build -t iseeku4ever/multi-client ./client
  - docker build -t iseeku4ever/multi-nginx ./nginx
  - docker build -t iseeku4ever/multi-server ./server
  - docker build -t iseeku4ever/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push iseeku4ever/multi-client
  - docker push iseeku4ever/multi-nginx
  - docker push iseeku4ever/multi-server
  - docker push iseeku4ever/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-920642279165
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
